#开启端口
server:
  port: 8879
#数据库配置
spring:
  ldap:
    urls: ldap://123.57.204.10:389/ #openldap连接地址
    username: cn=Directory Manager,c=cn #用户名
    password: Js3qCaLdapAdmin #密码
    base: #dc=super
  datasource:
    url: jdbc:sqlite:D:\工具\ldap.sqlite
    driver-class-name: org.sqlite.JDBC
    username:
    password:

  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB



filePath:
  clientToolPath: C:\Users\77512\Desktop\数字证书管理工具V1.12.22.1024-1.exe
  manualPath: C:\Users\77512\Desktop\安全备份系统安装手册-V3tax.docx
  configPath: C:\Users\77512\Desktop\aaaa\slapd.conf
  certPath: D:\工具\
  runPath: C:\Users\77512\Desktop\aaaa\slapd.service
ldap:
  searchFilter: (objectClass=*)
  searchBase: dc=super,dc=com
version:
  serviceVersion: "服务版本-2023-03-31 V1.0"
  clientVersion: "客户端版本-2023-03-31 V1.0"


login:
  timeout: 10000

token:
  validTime: 100


ldapLink:
  url: 123.57.204.10
  port: 389
  userName: cn=Directory Manager,c=cn
  password: Js3qCaLdapAdmin