#开启端口
server:
  port: 8879
#数据库配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    mvc:
      static-path-pattern: /**
  ldap:
    #    urls: ldap://39.98.83.34:389/ #openldap连接地址
    urls: ldap://123.57.204.10:389/ #openldap连接地址
    #    username: cn=root,dc=super,dc=com #用户名
    username: cn=Directory Manager,c=cn
    #    password: 123456 #密码
    password: Js3qCaLdapAdmin
    base: #dc=super
  datasource:
    #    url: jdbc:sqlite:D:\工具\ldap.sqlite
    url: jdbc:sqlite:E:\博雅\项目\LDAP\项目\ldap\ldap.sqlite
    driver-class-name: org.sqlite.JDBC
    username:
    password:

  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB



filePath:
  clientToolPath: C:\Users\77512\Desktop\数字证书管理工具V1.12.22.1024-1.exe
  manualPath: C:\Users\77512\Desktop\安全备份系统安装手册-V3tax.docx
  #configPath: C:\Users\77512\Desktop\aaaa\slapd.conf
  configPath: C:\Users\17529\Desktop\1\slapd.conf
  certPath: D:\工具\
  runPath: C:\Users\77512\Desktop\aaaa\slapd.service
  shPath:
ldap:
  searchFilter: (objectClass=*)
  searchBase: c=cn
version:
  serviceVersion: "服务版本-2023-03-31 V1.0"
  clientVersion: 1.12.22.1024-1


login:
  timeout: 10000

token:
  validTime: 1


ldapLink:
  url: 123.57.204.10
  port: 389
  userName: cn=Directory Manager,c=cn
  password: Js3qCaLdapAdmin